<template>
  <section class="scenario-page concept-page priority-creator-page">
    <header class="concept-heading"><div><span class="lab-eyebrow">Eksperyment · rzadki rytuał 8–18 min</span><h1>Utwórz kierunek, który naprawdę coś znaczy</h1><p>Kreator prowadzi od znaczenia przez mapę wsparcia do świadomie wybranych obiektów startowych.</p></div><span class="status-badge status-badge--experiment">Koncepcja · nie baseline</span></header>
    <section v-if="!finished" class="creator-wizard neo-card">
      <header class="creator-wizard__header"><div><span class="lab-eyebrow">Nowy priorytet</span><h2>{{ steps[currentStep].title }}</h2></div><span>Krok {{ currentStep + 1 }} z {{ steps.length }}</span></header>
      <ol class="creator-stepper"><li v-for="(step, index) in steps" :key="step.id" :class="{ active: index === currentStep, complete: index < currentStep }"><button type="button" @click="currentStep = index"><span><AppIcon v-if="index < currentStep" name="check" /><template v-else>{{ index + 1 }}</template></span><small>{{ step.short }}</small></button></li></ol>
      <div class="creator-wizard__body">
        <div v-if="currentStep === 0" class="creator-form-grid"><label class="full"><span>Nazwa kierunku</span><input v-model="form.title" /></label><label><span>Dlaczego właśnie teraz?</span><textarea v-model="form.whyNow" rows="5" /></label><label><span>Jakiej zmiany chcesz doświadczać?</span><textarea v-model="form.direction" rows="5" /></label><label class="full"><span>Co pozostaje w Twoim wpływie?</span><textarea v-model="form.influence" rows="3" /></label></div>
        <div v-else-if="currentStep === 1" class="creator-form-grid"><label class="full"><span>Czy ten kierunek ma naturalne zakończenie?</span><div class="choice-row"><button type="button" :class="{ active: form.endingType === 'open' }" @click="form.endingType = 'open'"><AppIcon name="all_inclusive" /><span><strong>Bezterminowy</strong><small>Coroczne potwierdzenie</small></span></button><button type="button" :class="{ active: form.endingType === 'natural' }" @click="form.endingType = 'natural'"><AppIcon name="flag" /><span><strong>Naturalne zakończenie</strong><small>Wydarzenie, nie wymuszony deadline</small></span></button></div></label><label v-if="form.endingType === 'natural'" class="full"><span>Po czym poznasz, że ten rozdział się zakończył?</span><textarea v-model="form.ending" rows="4" /></label><label><span>Sygnały progresu</span><textarea v-model="form.progress" rows="4" /></label><label><span>Sygnały ryzyka</span><textarea v-model="form.risks" rows="4" /></label></div>
        <div v-else-if="currentStep === 2" class="creator-form-grid"><label class="full"><span>Jakie kompromisy świadomie akceptujesz?</span><textarea v-model="form.tradeoffs" rows="5" /></label><div class="influence-board full"><article><AppIcon name="pan_tool" /><h3>Pod moim wpływem</h3><p>Rytm dnia, rozmowy, proszenie o wsparcie, dbanie o ciało.</p></article><article><AppIcon name="cloud" /><h3>Poza pełną kontrolą</h3><p>Biologia, decyzje innych osób i czas potrzebny na zmianę.</p></article></div></div>
        <div v-else-if="currentStep === 3" class="support-map-step"><header><div><h3>Zbuduj hipotezę wsparcia</h3><p>Propozycje są materiałem do namysłu — nie zobowiązaniem.</p></div><button type="button" class="tonal-control" @click="showAiConsent = true"><AppIcon name="auto_awesome" /> Poproś AI o propozycje</button></header><div v-if="showAiConsent" class="ai-consent-card"><AppIcon name="privacy_tip" /><div><strong>Jednorazowa zgoda</strong><p>AI otrzyma nazwę, znaczenie, zakres wpływu i sygnały. Niczego nie utworzy automatycznie.</p></div><button type="button" class="tonal-control" @click="aiGenerated = true; showAiConsent = false">Zgadzam się i generuję</button></div><div class="support-proposal-grid"><button v-for="proposal in proposals" :key="proposal.id" type="button" :class="{ selected: selectedProposals.has(proposal.id) }" @click="toggleProposal(proposal.id)"><AppIcon :name="selectedProposals.has(proposal.id) ? 'check_circle' : proposal.icon" /><span><small>{{ proposal.type }}</small><strong>{{ proposal.title }}</strong><p>{{ proposal.contribution }}</p><em>{{ proposal.signal }}</em></span></button></div><p v-if="aiGenerated" class="ai-result-note"><AppIcon name="auto_awesome" /> AI dodało propozycje, ale nadal Ty wybierasz obiekty startowe.</p></div>
        <div v-else-if="currentStep === 4" class="relation-step"><header><h3>Nazwij wkład każdej relacji</h3><p>Ten sam obiekt może wspierać kilka priorytetów na różne sposoby.</p></header><article v-for="proposal in selectedProposalList" :key="proposal.id" class="relation-editor"><AppIcon :name="proposal.icon" /><div><strong>{{ proposal.title }}</strong><small>{{ proposal.type }} · {{ proposal.role }}</small></div><label><span>Pomaga, ponieważ…</span><textarea v-model="proposal.contribution" rows="3" /></label><label><span>Oczekiwany sygnał</span><input v-model="proposal.signal" /></label></article></div>
        <div v-else-if="currentStep === 5" class="timeline-board"><p>Timeline porządkuje start, ale nie udaje przewidywalności szerokiego kierunku.</p><section v-for="horizon in ['Teraz', 'W tym miesiącu', 'Później']" :key="horizon"><h3>{{ horizon }}</h3><div><article v-for="proposal in timelineItems(horizon)" :key="proposal.id"><AppIcon :name="proposal.icon" /><span><strong>{{ proposal.title }}</strong><small>{{ proposal.type }}</small></span></article><button type="button"><AppIcon name="add" /> Przenieś obiekt tutaj</button></div></section></div>
        <div v-else class="creator-review"><article class="priority-review-card"><AppIcon name="north_star" /><div><span class="lab-eyebrow">Nowy priorytet</span><h3>{{ form.title }}</h3><p>{{ form.direction }}</p></div><span class="status-badge status-badge--ready">Gotowy do aktywacji</span></article><div class="review-columns"><section><h3>Znaczenie</h3><p>{{ form.whyNow }}</p><h3>Naturalne zakończenie</h3><p>{{ form.endingType === 'open' ? 'Bezterminowy, potwierdzany corocznie.' : form.ending }}</p></section><section><h3>Obiekty startowe</h3><article v-for="proposal in selectedProposalList" :key="proposal.id"><AppIcon :name="proposal.icon" /><span><strong>{{ proposal.title }}</strong><small>{{ proposal.contribution }}</small></span></article></section></div></div>
      </div>
      <footer class="creator-wizard__footer"><button type="button" class="lab-button lab-button--text" :disabled="currentStep === 0" @click="currentStep -= 1"><AppIcon name="arrow_back" /> Wstecz</button><button v-if="currentStep < steps.length - 1" type="button" class="lab-button lab-button--filled" @click="currentStep += 1">Dalej <AppIcon name="arrow_forward" /></button><button v-else type="button" class="lab-button lab-button--filled" @click="finished = true"><AppIcon name="rocket_launch" /> Utwórz priorytet i 3 obiekty</button></footer>
    </section>
    <section v-else class="creator-success neo-card"><AppIcon name="check_circle" /><span class="lab-eyebrow">Priorytet aktywny</span><h2>{{ form.title }}</h2><p>Utworzono kierunek i wybrane obiekty startowe. Każda relacja ma opis wkładu i oczekiwany sygnał.</p><button type="button" class="lab-button lab-button--tonal" @click="finished = false; currentStep = 0">Przejdź rytuał ponownie</button></section>
  </section>
</template>

<script setup lang="ts">
import { computed, reactive, ref } from 'vue'
import AppIcon from '@product/components/shared/AppIcon.vue'
const steps = [
  { id: 'meaning', short: 'Znaczenie', title: 'Nazwij to, co jest naprawdę ważne' }, { id: 'signals', short: 'Sygnały', title: 'Określ kierunek i naturalne zakończenie' }, { id: 'tradeoffs', short: 'Wpływ', title: 'Oddziel wpływ od tego, czego nie kontrolujesz' }, { id: 'support', short: 'Wsparcie', title: 'Zbuduj mapę możliwego wsparcia' }, { id: 'relations', short: 'Relacje', title: 'Wyjaśnij, jak każdy obiekt ma pomagać' }, { id: 'timeline', short: 'Timeline', title: 'Rozłóż start bez fałszywej precyzji' }, { id: 'review', short: 'Przegląd', title: 'Sprawdź zobowiązania przed aktywacją' },
]
const currentStep = ref(0); const finished = ref(false); const showAiConsent = ref(false); const aiGenerated = ref(false)
const form = reactive({ title: 'Dążenie do zajścia w ciążę', whyNow: 'Chcę podejść do tego etapu świadomie, z troską o relację, ciało i własny dobrostan.', direction: 'Więcej spokoju, poczucia przygotowania i bliskości zamiast chaosu oraz presji wyniku.', influence: 'Mogę dbać o zdrowie, regenerację, rozmowę, plan wsparcia i sposób przechodzenia przez niepewność.', endingType: 'natural', ending: 'Priorytet zakończy się naturalnie, kiedy uda się zajść w ciążę.', progress: 'Więcej spokoju, regularne wspierające praktyki, wspólne decyzje.', risks: 'Presja wyniku, przeciążenie trackingiem, unikanie trudnych rozmów.', tradeoffs: 'Mniej równoległych zobowiązań i więcej miejsca na regenerację.' })
const proposals = reactive([
  { id: 'care-plan', type: 'Cel', icon: 'flag', title: 'Ustalić osobisty plan przygotowań', role: 'Rezultat', contribution: 'Porządkuje działania pozostające pod moim wpływem i zmniejsza chaos.', signal: 'Plan uzgodniony i możliwy do wdrożenia', horizon: 'Teraz' },
  { id: 'walk', type: 'Nawyk', icon: 'routine', title: 'Spokojny spacer 4× w tygodniu', role: 'Praktyka', contribution: 'Wspiera ruch, regenerację i obniżanie napięcia bez presji wyniku.', signal: 'Więcej dni z energią ≥ 6/9', horizon: 'W tym miesiącu' },
  { id: 'energy', type: 'Tracker', icon: 'monitoring', title: 'Energia i napięcie', role: 'Sygnał', contribution: 'Pomaga zauważyć, czy plan wspiera, czy staje się obciążeniem.', signal: '3 krótkie wpisy w tygodniu', horizon: 'Teraz' },
  { id: 'talk', type: 'Intencja', icon: 'gps_fixed', title: 'Porozmawiać o granicach wsparcia', role: 'Eksperyment', contribution: 'Buduje wspólne rozumienie sposobu przechodzenia przez ten etap.', signal: 'Rozmowa i jedna wspólna decyzja', horizon: 'W tym miesiącu' },
])
const selectedProposals = ref(new Set(['care-plan', 'walk', 'energy']))
const selectedProposalList = computed(() => proposals.filter(item => selectedProposals.value.has(item.id)))
const toggleProposal = (id: string) => { const next = new Set(selectedProposals.value); next.has(id) ? next.delete(id) : next.add(id); selectedProposals.value = next }
const timelineItems = (horizon: string) => selectedProposalList.value.filter(item => item.horizon === horizon)
</script>
