<template>
  <section class="scenario-page concept-page priority-hub-page">
    <header class="priority-hero neo-card"><div><span class="priority-hero__icon"><AppIcon name="north_star" /></span><div><div><span class="status-badge status-badge--ready">Aktywny</span><span class="quiet-pill">Fokus lipca</span></div><h1>Dążenie do zajścia w ciążę</h1><p>Więcej spokoju, poczucia przygotowania i bliskości zamiast chaosu oraz presji wyniku.</p></div></div><div><button type="button" class="lab-button lab-button--tonal"><AppIcon name="edit" /> Edytuj</button><button type="button" class="lab-button lab-button--filled"><AppIcon name="auto_awesome" /> Miesięczny check-in</button></div></header>
    <div class="tab-control"><button :class="{ active: tab === 'overview' }" @click="tab = 'overview'">Przegląd</button><button :class="{ active: tab === 'support' }" @click="tab = 'support'">Mapa wsparcia</button><button :class="{ active: tab === 'reflection' }" @click="tab = 'reflection'">Refleksja</button></div>
    <div v-if="tab === 'overview'" class="hub-overview"><section class="neo-card direction-card"><header><AppIcon name="explore" /><span><strong>Kierunek</strong><small>Subiektywna ocena, nie procent ukończenia</small></span><select v-model="direction"><option>We właściwą stronę</option><option>Bez wyraźnej zmiany</option><option>Potrzebna korekta</option></select></header><p>W ostatnim miesiącu pojawiło się więcej spokoju i wspólnych decyzji. Nadal trudno utrzymać regenerację w intensywnych tygodniach.</p><div class="confidence"><span><strong>Pewność tej oceny</strong><small>{{ confidence }}/5</small></span><input v-model="confidence" type="range" min="1" max="5" /></div></section><section class="neo-card evidence-card-hub"><header><AppIcon name="fact_check" /><span><strong>Dowody</strong><small>Sygnały wspierające interpretację</small></span></header><div><article><AppIcon name="trending_up" /><span><strong>Energia stabilniejsza</strong><small>3 tygodnie danych · umiarkowany sygnał</small></span></article><article><AppIcon name="forum" /><span><strong>Dwie wspólne decyzje</strong><small>Dowód jakościowy z refleksji</small></span></article><article><AppIcon name="warning" /><span><strong>Napięcie wraca przy przeciążeniu</strong><small>Sygnał ryzyka pozostaje aktywny</small></span></article></div></section><section class="neo-card coverage-card"><header><AppIcon name="account_tree" /><span><strong>Pokrycie wsparciem</strong><small>Czy ważne aspekty mają swój środek?</small></span></header><div><span><strong>Przygotowanie</strong><progress max="100" value="75" /></span><span><strong>Regeneracja</strong><progress max="100" value="62" /></span><span><strong>Relacja</strong><progress max="100" value="82" /></span><span><strong>Radzenie sobie z niepewnością</strong><progress max="100" value="28" /></span></div><p><AppIcon name="lightbulb" /> Największa luka: praktyka pomagająca przechodzić przez niepewność.</p></section></div>
    <div v-else-if="tab === 'support'" class="support-hub-layout"><nav class="support-object-list"><button v-for="object in supportObjects" :key="object.id" type="button" :class="{ active: selectedObject === object.id }" @click="selectedObject = object.id"><AppIcon :name="object.icon" /><span><small>{{ object.type }} · {{ object.role }}</small><strong>{{ object.title }}</strong><em>{{ object.status }}</em></span><AppIcon name="chevron_right" /></button></nav><article class="relation-detail neo-card"><header><AppIcon :name="activeObject.icon" /><span><small>{{ activeObject.type }} · relacja</small><h2>{{ activeObject.title }}</h2></span><span class="status-badge status-badge--ready">Potwierdzona przeze mnie</span></header><label><span>Pomaga temu priorytetowi, ponieważ…</span><textarea v-model="activeObject.contribution" rows="5" /></label><div class="relation-fields"><label><span>Rola</span><select v-model="activeObject.role"><option>Rezultat</option><option>Praktyka</option><option>Sygnał</option><option>Eksperyment</option></select></label><label><span>Oczekiwany sygnał</span><input v-model="activeObject.signal" /></label></div><footer><span><strong>Historia relacji</strong><small>Utworzona 12 maja · potwierdzona 30 czerwca</small></span><button type="button" class="lab-button lab-button--tonal">Zapisz relację</button></footer></article></div>
    <div v-else class="reflection-timeline"><article v-for="item in reflections" :key="item.month" class="neo-card"><span class="timeline-dot"><AppIcon :name="item.icon" /></span><div><span class="lab-eyebrow">{{ item.month }}</span><h2>{{ item.course }}</h2><p>{{ item.note }}</p><footer><span>{{ item.confidence }}/5 pewność</span><span>{{ item.evidence }} dowody</span><button type="button" class="text-control">Otwórz refleksję <AppIcon name="arrow_forward" /></button></footer></div></article></div>
  </section>
</template>

<script setup lang="ts">
import { computed, reactive, ref } from 'vue'
import AppIcon from '@product/components/shared/AppIcon.vue'
const tab = ref<'overview' | 'support' | 'reflection'>('overview'); const direction = ref('We właściwą stronę'); const confidence = ref(4); const selectedObject = ref('care-plan')
const supportObjects = reactive([
  { id: 'care-plan', type: 'Cel', icon: 'flag', title: 'Ustalić osobisty plan przygotowań', role: 'Rezultat', contribution: 'Porządkuje działania pozostające pod moim wpływem i zmniejsza chaos.', signal: 'Plan uzgodniony i możliwy do wdrożenia', status: 'W toku' },
  { id: 'walk', type: 'Nawyk', icon: 'routine', title: 'Spokojny spacer 4× w tygodniu', role: 'Praktyka', contribution: 'Wspiera regularny ruch, regenerację i obniżanie napięcia.', signal: 'Więcej dni z energią ≥ 6/9', status: 'Stabilny' },
  { id: 'energy', type: 'Tracker', icon: 'monitoring', title: 'Energia i napięcie', role: 'Sygnał', contribution: 'Pomaga zauważyć, czy plan wspiera, czy staje się obciążeniem.', signal: '3 wpisy tygodniowo', status: 'Umiarkowane dane' },
  { id: 'talk', type: 'Intencja', icon: 'gps_fixed', title: 'Porozmawiać o granicach wsparcia', role: 'Eksperyment', contribution: 'Buduje wspólne rozumienie sposobu przechodzenia przez ten etap.', signal: 'Rozmowa i jedna wspólna decyzja', status: 'Na ten tydzień' },
])
const activeObject = computed(() => supportObjects.find(item => item.id === selectedObject.value) ?? supportObjects[0])
const reflections = [
  { month: 'Maj', icon: 'trending_flat', course: 'Bez wyraźnej zmiany', confidence: 2, evidence: 3, note: 'Dużo planowania, mało przestrzeni na regenerację. Mapa wsparcia wymaga uproszczenia.' },
  { month: 'Czerwiec', icon: 'north_east', course: 'We właściwą stronę', confidence: 3, evidence: 5, note: 'Spacery i wspólne decyzje zaczęły tworzyć spokojniejszy rytm.' },
  { month: 'Lipiec', icon: 'trending_up', course: 'We właściwą stronę', confidence: 4, evidence: 7, note: 'Więcej spokoju i lepsze rozpoznawanie sygnałów przeciążenia.' },
]
</script>
