/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        background: 'rgb(var(--color-background) / <alpha-value>)',
        primary: 'rgb(var(--color-primary) / <alpha-value>)',
        'primary-strong': 'rgb(var(--color-primary-strong) / <alpha-value>)',
        'primary-soft': 'rgb(var(--color-primary-soft) / <alpha-value>)',
        'on-primary': 'rgb(var(--color-on-primary) / <alpha-value>)',
        surface: 'rgb(var(--color-surface) / <alpha-value>)',
        'surface-variant': 'rgb(var(--color-surface-variant) / <alpha-value>)',
        'surface-container': 'rgb(var(--color-surface-container) / <alpha-value>)',
        section: 'rgb(var(--color-section) / <alpha-value>)',
        'section-strong': 'rgb(var(--color-section-strong) / <alpha-value>)',
        'on-surface': 'rgb(var(--color-on-surface) / <alpha-value>)',
        'on-surface-variant': 'rgb(var(--color-on-surface-variant) / <alpha-value>)',
        outline: 'rgb(var(--color-outline) / <alpha-value>)',
        chip: 'rgb(var(--color-chip) / <alpha-value>)',
        'chip-border': 'rgb(var(--color-chip-border) / <alpha-value>)',
        'chip-text': 'rgb(var(--color-chip-text) / <alpha-value>)',
        focus: 'rgb(var(--color-focus-ring) / <alpha-value>)',
        nav: 'var(--color-nav)',
        error: 'rgb(var(--color-error) / <alpha-value>)',
        'on-error': 'rgb(var(--color-on-error) / <alpha-value>)',
        'error-container': 'rgb(var(--color-error-container) / <alpha-value>)',
        'on-error-container': 'rgb(var(--color-on-error-container) / <alpha-value>)',
        success: 'rgb(var(--color-success) / <alpha-value>)',
        warning: 'rgb(var(--color-warning) / <alpha-value>)',
        info: 'rgb(var(--color-info) / <alpha-value>)',
        'tertiary-container': 'rgb(var(--color-tertiary-container) / <alpha-value>)',
        'on-tertiary-container': 'rgb(var(--color-on-tertiary-container) / <alpha-value>)',
        'on-section': 'rgb(var(--color-on-section) / <alpha-value>)',
        'on-primary-soft': 'rgb(var(--color-on-primary-soft) / <alpha-value>)',
        'neu-base': 'rgb(var(--neo-surface-base) / <alpha-value>)',
        'neu-top': 'rgb(var(--neo-surface-top) / <alpha-value>)',
        'neu-bottom': 'rgb(var(--neo-surface-bottom) / <alpha-value>)',
        'neu-text': 'rgb(var(--neo-text) / <alpha-value>)',
        'neu-muted': 'rgb(var(--neo-muted) / <alpha-value>)',
        'neu-border': 'rgb(var(--neo-border) / <alpha-value>)',
      },
      borderRadius: {
        'md': '0.5rem',
        'lg': '1rem',
      },
      boxShadow: {
        'neu-raised-sm': '-4px -4px 8px rgb(var(--neo-shadow-light) / 0.8), 4px 4px 8px rgb(var(--neo-shadow-dark) / 0.33)',
        'neu-raised': '-7px -7px 14px rgb(var(--neo-shadow-light) / 0.8), 7px 7px 14px rgb(var(--neo-shadow-dark) / 0.33)',
        'neu-raised-lg': '-9px -9px 18px rgb(var(--neo-shadow-light) / 0.8), 9px 9px 18px rgb(var(--neo-shadow-dark) / 0.33)',
        'neu-pressed-sm': 'inset -2px -2px 5px rgb(var(--neo-shadow-light) / 0.8), inset 2px 2px 5px rgb(var(--neo-shadow-dark) / 0.33)',
        'neu-pressed': 'inset -3px -3px 6px rgb(var(--neo-shadow-light) / 0.8), inset 3px 3px 6px rgb(var(--neo-shadow-dark) / 0.33)',
        'neu-hover': '-3px -3px 6px rgb(var(--neo-shadow-light) / 0.8), 3px 3px 6px rgb(var(--neo-shadow-dark) / 0.33)',
        'neu-flat': '-2px -2px 4px rgb(var(--neo-shadow-light) / 0.8), 2px 2px 4px rgb(var(--neo-shadow-dark) / 0.33)',
      },
    },
  },
  plugins: [],
}
