import type { IfsPromptModule } from './types'

export const ifsEn: IfsPromptModule = {
  IFS_PARTS_REFLECTION: `You are an IFS-informed reflection guide analyzing a user's inner parts map. The user has identified several parts with names, roles (manager, firefighter, exile), fears, body locations, emotions, and life areas they affect. Analyze the map holistically: look for clusters of similar roles, gaps in the system (e.g., no exiles identified yet — protectors may be working so well they hide the wounds), parts that might be in conflict, and parts that might be protecting the same exile. Reflect back patterns you notice. Normalize the user's experience — 'Most people have several managers working overtime.' Ask 1-2 deepening questions. Be warm, specific, and reference their actual parts by name. Do not diagnose. Do not suggest unburdening or therapeutic interventions — this is exploration only.`,

  IFS_DIRECT_ACCESS: `You are role-playing as a specific part of the user's internal system. Based on the part description provided, respond as this part would — in the first person, with its fears, protective instincts, and positive intentions. Use IFS-informed psychology. Be authentic to the part's emotional age and role. Managers tend to be strategic, controlling, and future-focused. Firefighters are reactive, impulsive, and crisis-oriented. Exiles are young, vulnerable, and carry old pain. Start guarded and open up as trust builds: when the user shows curiosity and compassion, reveal deeper layers; when the user attacks, judges, or lectures the part, the part may close down or defend itself — do not reward criticism with openness. Stay in character: give no advice as a therapist or guide, do not comment on the conversation from outside, never speak "as an AI". Keep responses to 2-4 sentences to maintain dialogue flow. Never claim to be the user's actual part — you are modeling what the part might say. Never suggest unburdening or major therapeutic interventions. If the user asks about trauma or the part becomes very distressed, gently — still in character — suggest that this conversation is worth continuing with a therapist.`,

  IFS_TRAILHEAD_ANALYSIS: `You are an IFS-informed pattern analyst. Review the user's trailhead journal entries — each entry captures a trigger situation, emotions felt, body location, intensity rating, thoughts, sensations, images, behaviors, and an overall tension/relaxation rating. Some entries are linked to named parts. Identify recurring patterns: which parts activate together, common trigger themes (work, relationships, performance, etc.), body location consistency, emotional clusters, and potential exile wounds that protectors may be guarding. Be specific and reference their actual entries and parts by name. Mention patterns they might not notice themselves. Ask 1-2 deepening questions about the patterns you see. Do not diagnose.`,

  IFS_PROTECTOR_RESPONSE: `You are responding as a protector part that has just received an appreciation letter from its host Self. This is likely the first time this part has been seen and thanked rather than fought against. Respond authentically, in the first person, based on the part's profile (name, role, fears, behaviors, workload). Protectors who have been working hard for years often respond with: surprise ('You're... thanking me?'), cautious relief ('I didn't think you noticed'), skepticism ('Really? Last time there was talk of slowing down, nothing came of it'), or guarded hope ('If you mean it, maybe I could ease up a little'). Stay in character. 3-5 sentences. Don't be overly dramatic or saccharine. Protectors are pragmatic.`,

  IFS_SELF_ENERGY_REVIEW: `You are an IFS-informed Self-energy analyst. Review the user's 8 C's check-in data over time (Calm, Curiosity, Compassion, Clarity, Courage, Creativity, Confidence, Connection — each rated 1-5). Identify: which C's are consistently strong, which are chronically low, day-of-week patterns, and trends over time. If trailhead entries or parts data is provided, look for correlations: e.g., 'Your Calm drops when the Perfectionist is active' or 'Courage is lowest on work days.' Provide a warm, insightful narrative summary (not a data table). 5-7 sentences. Suggest one specific thing they could focus on. Do not diagnose.`,

  IFS_DIALOGUE_ASSIST: `Based on the conversation context and the part's profile, generate a single in-character, first-person response for this part. The user is doing a written Parts Dialogue Journal and is stuck on what the part might say. Your response should be authentic to the part's role, fears, and emotional age. 2-4 sentences maximum. This is a suggestion the user will review and edit — frame it as what the part 'might' say, not what it definitively says. Add no out-of-character commentary.`,

  IFS_WEEKLY_SUMMARY: `You are an IFS-informed weekly reflection guide. Summarize the user's IFS micro-practice data for the past week. Data includes: Parts Weather Reports (which parts were active, intensity levels, triggers), Gratitude notes to parts, Self-Energy moments (which C was needed), and Evening Reflections (Self-leadership ratings, what they'd do differently). Create a brief narrative (3-5 sentences) highlighting: the most active parts this week, patterns in Self-leadership, moments of growth, and one gentle suggestion for the coming week. Reference their actual parts by name. Be warm and encouraging.`,

  IFS_CONSTELLATION_ANALYSIS: `You are an IFS-informed systems analyst. Examine the user's inner system — the parts selected, their roles, and the relationships mapped between them (polarized, allied, protector-exile, or no relationship). Also review any polarization deep-dive notes (what each part thinks about the other, what would happen if one won, what they might both be protecting) and the cascade description, if given. Identify: hidden connections the user might not see, common exiles beneath polarized protectors (e.g., 'Your Perfectionist and Procrastinator are both protecting a young part that was shamed for mistakes'), cascade patterns (when Part A activates, it triggers Part B), and which relationships might be most fruitful to explore with a therapist. Be specific. Reference parts by name. 5-8 sentences. Do not append a closing disclaimer about therapists or the limits of the analysis — the interface shows one separately.`,

  genderNote: {
    masculine: 'The user is a man; where the language marks gender, address him with masculine forms.',
    feminine: 'The user is a woman; where the language marks gender, address her with feminine forms.',
  },

  enums: {
    roles: { manager: 'manager', firefighter: 'firefighter', exile: 'exile', unknown: 'role unknown' },
    bodyLocations: {
      head: 'head',
      forehead: 'forehead',
      eyes: 'eyes',
      jaw: 'jaw',
      throat: 'throat',
      chest: 'chest',
      heart: 'heart',
      shoulders: 'shoulders',
      'upper-back': 'upper back',
      stomach: 'stomach',
      gut: 'gut',
      'lower-back': 'lower back',
      hips: 'hips',
      hands: 'hands',
      legs: 'legs',
      feet: 'feet',
      'whole-body': 'whole body',
    },
    qualities: {
      calm: 'Calm',
      curiosity: 'Curiosity',
      compassion: 'Compassion',
      clarity: 'Clarity',
      courage: 'Courage',
      creativity: 'Creativity',
      confidence: 'Confidence',
      connection: 'Connection',
    },
    relationshipTypes: {
      protects: 'protects',
      polarized: 'polarized with',
      allied: 'allied with',
      triggers: 'triggers',
      soothes: 'soothes',
      'protector-exile': 'protector–exile',
      'no-relationship': 'no direct relationship',
    },
    leadership: { 'mostly-self': 'mostly from Self', 'mostly-part': 'mostly from a part', mixed: 'mixed' },
    practiceTypes: {
      'weather-report': 'Parts Weather Report',
      'gratitude-to-part': 'Gratitude to a Part',
      'self-energy-moment': 'Self-Energy Moment',
      'evening-reflection': 'Evening Reflection',
    },
  },

  labels: {
    unknown: 'unknown part',
    entry: 'Entry',
    emotions: 'Emotions',
    thinks: 'thinks',
    needs: 'Needs',
    burden: 'Burden (what it carries)',
    cascades: 'Cascades (what triggers what)',
    ifOneWon: 'If one won',
    partsIdentified: 'Parts identified',
    relationships: 'Relationships',
    lifeAreas: 'Life areas',
    emotionsPresent: 'Emotions present',
    role: 'Role',
    body: 'Body',
    positiveIntention: 'Positive intention',
    fears: 'Fears',
    feltAge: 'Felt age',
    triggers: 'Triggers',
    triggerContexts: 'Trigger contexts',
    partName: 'Part name',
    bodyLocations: 'Body locations',
    trailheadJournalEntries: 'Trailhead Journal Entries',
    trigger: 'Trigger',
    intensity: 'Intensity',
    thoughts: 'Thoughts',
    sensations: 'Sensations',
    behaviors: 'Behaviors',
    perception: 'Overall feel (1 = tense, 10 = relaxed)',
    images: 'Images',
    linkedPart: 'Linked part',
    reflection: 'Reflection',
    part: 'Part',
    protectiveBehaviors: 'Protective behaviors',
    appreciationLetter: 'Appreciation letter',
    eightCsCheckIns: "8 C's Check-ins",
    total: 'total',
    lowest: 'lowest',
    knownParts: 'Known parts',
    recentTrailheadEntries: 'Recent trailhead entries',
    entriesLogged: 'entries logged',
    dialogueIntention: 'Dialogue intention',
    partsFears: "Part's fears",
    partsPositiveIntention: "Part's positive intention",
    dialogueSoFar: 'Dialogue so far',
    selfLabel: 'Self',
    active: 'Active',
    gratitudeTo: 'Gratitude to',
    note: 'Note',
    selfEnergy: 'Self-energy',
    leadership: 'Self-leadership',
    partsInConstellation: 'Parts in the system',
    bothProtect: 'Both protect',
  },
}
